//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Product
    {
        public int ID { get; set; }
        [Required(ErrorMessage = "Product name required")]
        [RegularExpression("[a-zA-Z][a-zA-Z ]+[a-zA-Z]$",ErrorMessage ="Only alphabates allowed")]
        public string ProductName { get; set; }
        [Required(ErrorMessage = "Price required")]
        [RegularExpression(@"^[0-9]*(\.[0-9]{0,2})?$", ErrorMessage = "Positive numbers upto two decimal places can be taken")]
        public Nullable<decimal> Price { get; set; }
        [Required(ErrorMessage = "Category required")]
        public string Category { get; set; }
        [Required(ErrorMessage = "Currency required")]
        public string Currency { get; set; }
        [Required(ErrorMessage = "Unit required")]
        public string Unit { get; set; }
        [Required(ErrorMessage = "Quantity required")]
        [RegularExpression("^[0-9]*$", ErrorMessage = "Only numbers are allowed")]
        public Nullable<int> Qty { get; set; }
    
        public virtual Category Category1 { get; set; }
        public virtual Currency Currency1 { get; set; }
        public virtual Unit Unit1 { get; set; }
    }
}
